from settings import *

PROJECTOR_CREATE_PROJECT_ASYNCHRONOUSLY = False
PROJECTOR_SEND_MAIL_ASYNCHRONOUSELY = False
PROJECTOR_DEFAULT_PROJECT_WORKFLOW = 'projector.tests.workflow.TestWorkflow'

DJALOG_LEVEL = 5

